# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KoreaNow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KoreaNow
    pod 'SnapKit', '~> 5.0.0'
    pod 'Alamofire', '~> 5.2'
    pod 'Kingfisher', '~> 5.0'
    pod 'Toast-Swift', '~> 5.0.1'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
end
